### PR TITLE
Throw an AuthError instead of TypeError when using an invalid school url

### LINKED ISSUE #114: Weird error on incorrect login
To reproduce try the following code:
```javascript
login: async function(mAuth) {
    this.magister = await magister({
        school: {
            url: 'https://' + this.get('school') + '.magister.net'
        },
        username: this.get('username'),
        password: this.get('password'),
        authCode: mAuth
    });
    return this;
}
```
Which will give the the following error:
```
Unhandled rejection TypeError: Cannot read property 'split' of null
    at Magister.login (C:\Users\Kasper\git\magbot3\node_modules\magister.js\lib\magister.js:581:59)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Perhaps we can handle the response a bit better?

### PR DESCRIPTION
**Pull request by Argetan**
Closes #114.

### CODE REVIEW

File: src/magister.js [hunk 1]
```diff
@@ -439,17 +439,28 @@ class Magister {
...
+				.split('?')[1]
+				.split('&')[0]
+				.split('=')[1]
+			xsrf =
+				xsrfResponse.headers.get('set-cookie')
+				.split('XSRF-TOKEN=')[1]
+				.split(';')[0]
+			authCookies = xsrfResponse.headers.get('set-cookie').toString()
+		} catch (err) {
+			if (err.message === 'Cannot read property \'split\' of null') {
```
Comment (lieuwex) [inline src/magister.js]: I feel like this is a bit ugly, but whatever. :P

**Comment by lieuwex** [comment]
Thanks!
